---
- hosts: all

  vars:
    bleachbit_url: https://download.bleachbit.org/BleachBit-2.2-portable.zip

  roles:
    - role: ansible-role-virtio-win
      virtio_win_iso_path: 'E:\\'
      when: ansible_system_vendor == "QEMU"

  tasks:
    - name: Enable Remote Desktop
      win_regedit:
        key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
        value: fDenyTSConnections
        data: 0
        datatype: dword

    - name: Allow connections from computers running any version of Remote Desktop (less secure)
      win_regedit:
        key: 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp'
        value: UserAuthentication
        data: 0
        datatype: dword

    - name: Enable Firewall Inbound Rules Group
      win_shell: Enable-NetFirewallRule -DisplayGroup "{{ item }}"
      loop:
        - Remote Desktop
        - Windows Remote Management

    - name: Use the plaintext WinRM transport and force it to use basic authentication
      win_shell: winrm set winrm/config/service '@{AllowUnencrypted="true"}'

    - name: Enable Administrator account
      win_user:
        name: Administrator
        account_disabled: no
      when: ansible_distribution is search("Microsoft Windows 10")

    - name: Remove all current pagefiles
      win_pagefile:
        remove_all: yes
        automatic: no
        state: absent

    - name: Disable Hibernate Mode
      win_command: powercfg -h off
      changed_when: false
      when: ansible_distribution is search("Microsoft Windows 10")

    - name: Install windows updates
      win_updates:
        category_names:
          - Application
          - Connectors
          - CriticalUpdates
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - SecurityUpdates
          - ServicePacks
          - Tools
          - UpdateRollups
          - Updates
        reboot: yes
        reboot_timeout: 10000
      register: windows_updates

    - name: Windows reboot
      win_reboot:
        reboot_timeout: 10000
      when: windows_updates.reboot_required and allow_windows_reboot_during_win_updates
